### ISSUE TITLE
size mismatch, m1: [16 x 2048], m2: [1024 x 15820]

### ISSUE THREAD

**Issue by ZamSul** [Yu-Wu/One-Example-Person-ReID#8]
Hi, I am trying your code on the duke dataset but I am getting the following error.

```
/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Files already downloaded and verified
Duke dataset loaded
  subset   | # ids | # tracklets
  ---------------------------
  train    |   702 |    16522
  query    |   702 |     2228
  gallery  |  1110 |    17661
  labeled    | N/A |      702
  unlabeled  | N/A |    15820

Create new one-shot split and save it to ./examples/duke_init_-1.pickle
Runing: EF=10%, step 0:	 Nums_to_be_select 1582 	 Ritio 	 Logs-dir 0.1
create dataloader for Training with batch_size 16
create dataloader for Training with batch_size 16
Traceback (most recent call last):
  File "run.py", line 124, in <module>
    main(parser.parse_args())
  File "run.py", line 88, in main
    eug.train(new_train_data, unselected_data, step, loss=args.loss, epochs=args.epochs, step_size=args.step_size, init_lr=0.1) if step != resume_step else eug.resume(ckpt_file, step)
  File "/home/zamra/PYreps/Person_ReId/One-Example-Person-ReID/my_reid/eug.py", line 92, in train
    return self.softmax_train(train_data, unselected_data, step, epochs, step_size, init_lr, dropout, loss)
  File "/home/zamra/PYreps/Person_ReId/One-Example-Person-ReID/my_reid/eug.py", line 142, in softmax_train
    trainer.train(epoch, s_dataloader, u_dataloader, optimizer, use_unselcted_data, print_freq=len(s_dataloader)//2)
  File "/home/zamra/PYreps/Person_ReId/One-Example-Person-ReID/my_reid/trainers.py", line 67, in train
    u_loss, u_prec1 = self._forward(u_inputs, u_targets, 'u')
  File "/home/zamra/PYreps/Person_ReId/One-Example-Person-ReID/my_reid/trainers.py", line 114, in _forward
    u_loss, outputs = self.u_criterion(u_feats, targets)
  File "/home/zamra/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zamra/PYreps/Person_ReId/One-Example-Person-ReID/my_reid/exclusive_loss.py", line 36, in forward
    outputs = Exclusive(self.V)(inputs, targets) * self.t
  File "/home/zamra/PYreps/Person_ReId/One-Example-Person-ReID/my_reid/exclusive_loss.py", line 15, in forward
    outputs = inputs.mm(self.V.t())
RuntimeError: size mismatch, m1: [16 x 2048], m2: [1024 x 15820] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:266
```

**Comment by Yu-Wu** [comment]
@ZamSul 

Sorry for my late reply. Have you solved this issue?
